window.__REPORT_DATA__ = {
  "status" : "FAILURE",
  "suiteName" : null,
  "sourceFile" : null,
  "tests" : 0,
  "failures" : 0,
  "errors" : 0,
  "skipped" : 0,
  "durationSeconds" : null,
  "updatedAt" : "2026-06-17T06:52:43.061Z",
  "primaryIssue" : "Declaration failed.",
  "testCases" : [ ],
  "batchSummary" : {
    "total" : 1,
    "successes" : 0,
    "issues" : 0,
    "failures" : 1,
    "drafts" : 0
  },
  "batchCases" : [ {
    "index" : 1,
    "status" : "ISSUE",
    "message" : "Validation Failed: Please fill in all required fields before submitting: PartyIdentification must be present ExporterParty ID is mandatory",
    "declarationTypeCode" : "COO",
    "declarationTypeDisplay" : "Certificate of Origin (COO)",
    "jobStatus" : "FLD",
    "jobId" : null,
    "declarationNumber" : "TDX2606120122",
    "pmtNumber" : null,
    "jobCreatedBy" : "mohan",
    "responseMessage" : "Validation Failed: Please fill in all required fields before submitting: PartyIdentification must be present ExporterParty ID is mandatory",
    "errorMessage" : "Validation Failed:",
    "responseSummary" : "Job ID: N/A\r\n\r\nMessage Ref: TDX2606120122\r\n\r\nDeclaration Type: COO\r\n\r\nStatus: FLD\r\n\r\nPMT Number: N/A\r\n\r\nJob Created By: mohan\r\n\r\nResponse Message: Validation Failed: Please fill in all required fields before submitting: PartyIdentification must be present ExporterParty ID is mandatory\r\n\r\nError Message: Validation Failed:",
    "toastText" : "Validation Failed:",
    "invalidCount" : 0,
    "diagnosticsText" : "{\r\n  \"toastText\" : \"Validation Failed:\",\r\n  \"responseMessage\" : \"Validation Failed: Please fill in all required fields before submitting: PartyIdentification must be present ExporterParty ID is mandatory\",\r\n  \"errorMessage\" : \"Validation Failed:\",\r\n  \"notificationMessages\" : [ \"Validation Failed: Please fill in all required fields before submitting: PartyIdentification must be present ExporterParty ID is mandatory\" ],\r\n  \"invalidElements\" : [ ],\r\n  \"supplyIndicator\" : null,\r\n  \"jobStatus\" : \"FLD\",\r\n  \"declarationType\" : \"COO\",\r\n  \"declarationNumber\" : \"TDX2606120122\",\r\n  \"jobCreatedBy\" : \"mohan\",\r\n  \"responseSummary\" : \"Job ID: N/A\\r\\n\\r\\nMessage Ref: TDX2606120122\\r\\n\\r\\nDeclaration Type: COO\\r\\n\\r\\nStatus: FLD\\r\\n\\r\\nPMT Number: N/A\\r\\n\\r\\nJob Created By: mohan\\r\\n\\r\\nResponse Message: Validation Failed: Please fill in all required fields before submitting: PartyIdentification must be present ExporterParty ID is mandatory\\r\\n\\r\\nError Message: Validation Failed:\"\r\n}",
    "diagnosticsFile" : "coo-batch-submit-validation-1.json",
    "screenshotFile" : "coo-batch-submit-1.png",
    "statusScreenshotFile" : "coo-batch-submit-status-1.png",
    "updatedAt" : "2026-06-17T06:52:43.061Z",
    "updatedAtMillis" : 1781679163061
  } ]
};
